language: java
dist: trusty
jdk:
  - openjdk8
script: xvfb-run mvn verify -B

# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2

# Deploy build
deploy:
- provider: script
  skip_cleanup: true # to upload artifacts created during the build
  script: bash bintray.sh
  on: release
      